### ISSUE TITLE
Home page (Latest news section) : Text is not displaying in Itouch and Samsung E7

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/Allplant-Auto-Electrics#12]
![e7_1](https://cloud.githubusercontent.com/assets/13309806/11466490/1ec4e00e-96f6-11e5-9a75-cd74be90d4af.png)
![t1](https://cloud.githubusercontent.com/assets/13309806/11466495/27a89210-96f6-11e5-9600-07fb58b2ec38.png)

**Comment by nakul-titan** [comment]
As width is very small, the text is made hidden in portrait view.

**Comment by ravi-josyula** [comment]
Implement the navigation icons layouts as it appears Samsung E7(have a look on above 1st screenshot) for look and feel purpose.

![qa](https://cloud.githubusercontent.com/assets/13309806/11619135/11b42934-9c59-11e5-95fb-794aea3d09b2.png)
