### ISSUE TITLE
Admin(Lead-ins) : All lead-ins are not displaying when added in admin panel

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/Allplant-Auto-Electrics#23]
![4](https://cloud.githubusercontent.com/assets/13309806/11495598/5fef8b9e-97c1-11e5-8f10-0f3b3584d531.png)

**Comment by nakul-titan** [comment]
Leadins have a limit of 3 as per ps because of that it is displaying only 3 leadins.

**Comment by ravi-josyula** [comment]
If there is limit for Lead-ins, then newly added lead-in should display first.

**Comment by nakul-titan** [comment]
As per Titan's standard post order should be ‘orderby’ => ‘menu_order title’ ‘order’ => ‘ASC’ and lead-ins are ordered accordingly.
