### ISSUE TITLE
Admin(Testing page) : Ordered and unordered lists are not styled

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/Allplant-Auto-Electrics#26]
![9](https://cloud.githubusercontent.com/assets/13309806/11495765/9a19f63c-97c2-11e5-8bd4-c966ee723b49.png)

**Comment by ravi-josyula** [comment]
Still bug is not fixed
![26](https://cloud.githubusercontent.com/assets/13309806/11619271/b81fc6b0-9c5a-11e5-95e8-5ee391f1ddc5.png)

**Comment by nakul-titan** [comment]
Unordered list has 100px padding left as per PSD
![ul](https://cloud.githubusercontent.com/assets/13461911/11629854/8ae7b6a0-9d20-11e5-92d7-eb11809bb7f3.png)
