### ISSUE TITLE
Contact Us page: Place holders should be vertically centered in Ipad and Ipad(mini)

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/Allplant-Auto-Electrics#3]
Browsers : IE9, Safari, Opera and Chrome

![pm5](https://cloud.githubusercontent.com/assets/13309806/11466020/f0d2ff30-96f2-11e5-82fb-8f0f4ef6fd24.png)

![10](https://cloud.githubusercontent.com/assets/13309806/11466024/fa2392ac-96f2-11e5-9a4d-d6b2b5e7d237.png)

**Comment by ravi-josyula** [comment]
Still bug is not fixed in IE9
![3 ie9](https://cloud.githubusercontent.com/assets/13309806/11618919/14166c6c-9c56-11e5-9760-b1298f5b13e5.png)

**Comment by nakul-titan** [comment]
It is working fine at my end, Please try hard refresh.
![contact-test](https://cloud.githubusercontent.com/assets/13461911/11630670/7c9aa388-9d24-11e5-910f-6c522aedbe0c.png)
