### ISSUE TITLE
Rencool page : Active state is not implemented properly 

### ISSUE THREAD

**Issue by ravi-josyula** [titan-cebu/Allplant-Auto-Electrics#34]
![desktop 4](https://cloud.githubusercontent.com/assets/13309806/11496160/f8886f4e-97c4-11e5-915d-678a01fba071.png)

**Comment by nakul-titan** [comment]
As Services is grand parent of Rencool it is showing active state to services as well.

**Comment by ravi-josyula** [comment]
Active state is still incorrect If try to open Gallery page also, Check the screenshot & fix it properly
thanks!
![2015-12-10_0947](https://cloud.githubusercontent.com/assets/13309806/11706896/22d9f88c-9eb2-11e5-9de6-67cc89a7812d.png)
